export { openDB, isIndexedDBAvailable } from './db'
export { saveWork, loadWork, getAllWorks, deleteWork } from './work-store'
export type { WorkMetadata, StoredWork } from './work-store'
export { saveAsset, getAsset, getAssetURL, deleteAsset, getAllAssets, getTotalAssetSize } from './asset-store'
export type { AssetMetadata, StoredAsset } from './asset-store'
export { migrateFromLocalStorage } from './migration'