/**
 * SubSilicon 官方素材库
 *
 * 提供免费可商用的素材资源，供创作者在编辑器中浏览和使用。
 * 背景图与角色立绘使用 picsum.photos 的 seed 功能生成稳定图片，
 * 音效仅提供元数据，需创作者自行上传音频文件。
 */

export type AssetCategory = 'background' | 'character' | 'item' | 'scene' | 'audio' | 'effect'
export type AssetLicense = 'free' | 'cc0' | 'cc-by' | 'commercial'

export interface LibraryAsset {
  id: string
  name: string
  category: AssetCategory
  license: AssetLicense
  thumbnailUrl: string  // 缩略图URL
  fullUrl: string  // 完整资源URL
  tags: string[]  // 标签
  description: string
  author?: string  // 来源作者
  source: string  // 来源网站
  dimensions?: { width: number; height: number }
  fileType: 'image' | 'audio' | 'video'
  fileSize?: string
}

const PICSUM_BASE = 'https://picsum.photos/seed'

/**
 * 背景图素材（30 个）
 * 使用 picsum.photos seed 生成 1280x720 稳定背景图
 */
const BACKGROUND_ASSETS: LibraryAsset[] = [
  {
    id: 'bg-01',
    name: '咖啡馆午后',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/cafe-afternoon/400/225`,
    fullUrl: `${PICSUM_BASE}/cafe-afternoon/1280/720`,
    tags: ['室内', '咖啡馆', '温暖', '日常'],
    description: '温暖色调的咖啡馆室内场景，适合日常对话与约会剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-02',
    name: '城市夜景',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/city-night/400/225`,
    fullUrl: `${PICSUM_BASE}/city-night/1280/720`,
    tags: ['室外', '城市', '夜景', '霓虹'],
    description: '霓虹闪烁的城市夜景，适合悬疑、赛博朋克故事。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-03',
    name: '校园走廊',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/school-corridor/400/225`,
    fullUrl: `${PICSUM_BASE}/school-corridor/1280/720`,
    tags: ['室内', '学校', '日常', '青春'],
    description: '阳光透过窗户的校园走廊，适合青春校园剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-04',
    name: '公园晨光',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/park-morning/400/225`,
    fullUrl: `${PICSUM_BASE}/park-morning/1280/720`,
    tags: ['室外', '公园', '自然', '清晨'],
    description: '清晨的公园绿地，适合治愈系、回忆场景。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-05',
    name: '街道黄昏',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/street-dusk/400/225`,
    fullUrl: `${PICSUM_BASE}/street-dusk/1280/720`,
    tags: ['室外', '街道', '黄昏', '城市'],
    description: '黄昏时分的城市街道，适合告别、回忆剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-06',
    name: '温馨卧室',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/cozy-bedroom/400/225`,
    fullUrl: `${PICSUM_BASE}/cozy-bedroom/1280/720`,
    tags: ['室内', '房间', '温馨', '日常'],
    description: '温馨的卧室场景，适合私密对话、内心独白。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-07',
    name: '图书馆',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/library-quiet/400/225`,
    fullUrl: `${PICSUM_BASE}/library-quiet/1280/720`,
    tags: ['室内', '图书馆', '学校', '安静'],
    description: '安静的图书馆场景，适合学习、思考剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-08',
    name: '海边夕阳',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/seaside-sunset/400/225`,
    fullUrl: `${PICSUM_BASE}/seaside-sunset/1280/720`,
    tags: ['室外', '海边', '夕阳', '自然'],
    description: '海边夕阳景色，适合告白、结局场景。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-09',
    name: '森林小径',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/forest-path/400/225`,
    fullUrl: `${PICSUM_BASE}/forest-path/1280/720`,
    tags: ['室外', '森林', '自然', '冒险'],
    description: '幽静的森林小径，适合冒险、奇幻剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-10',
    name: '雪山顶峰',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/snow-mountain/400/225`,
    fullUrl: `${PICSUM_BASE}/snow-mountain/1280/720`,
    tags: ['室外', '雪山', '自然', '冒险'],
    description: '壮丽的雪山景色，适合史诗、冒险剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-11',
    name: '老式教室',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/old-classroom/400/225`,
    fullUrl: `${PICSUM_BASE}/old-classroom/1280/720`,
    tags: ['室内', '学校', '教室', '复古'],
    description: '复古风格的老式教室，适合回忆、年代剧。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-12',
    name: '现代办公室',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/modern-office/400/225`,
    fullUrl: `${PICSUM_BASE}/modern-office/1280/720`,
    tags: ['室内', '办公室', '城市', '职场'],
    description: '现代风格的办公空间，适合职场、商战剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-13',
    name: '医院走廊',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/hospital-hall/400/225`,
    fullUrl: `${PICSUM_BASE}/hospital-hall/1280/720`,
    tags: ['室内', '医院', '城市', '严肃'],
    description: '冷色调的医院走廊，适合严肃、悲伤剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-14',
    name: '繁华商业街',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/busy-street/400/225`,
    fullUrl: `${PICSUM_BASE}/busy-street/1280/720`,
    tags: ['室外', '街道', '城市', '繁华'],
    description: '人流如织的商业街，适合都市日常剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-15',
    name: '古朴神社',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/shrine-ancient/400/225`,
    fullUrl: `${PICSUM_BASE}/shrine-ancient/1280/720`,
    tags: ['室外', '神社', '复古', '神秘'],
    description: '古朴的神社建筑，适合奇幻、恋爱剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-16',
    name: '雨夜小巷',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/rainy-alley/400/225`,
    fullUrl: `${PICSUM_BASE}/rainy-alley/1280/720`,
    tags: ['室外', '街道', '夜景', '雨'],
    description: '雨夜的小巷，适合悬疑、追逐剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-17',
    name: '山顶神殿',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/mountain-temple/400/225`,
    fullUrl: `${PICSUM_BASE}/mountain-temple/1280/720`,
    tags: ['室外', '神殿', '山', '神秘'],
    description: '云雾缭绕的山顶神殿，适合奇幻、修行剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-18',
    name: '湖畔清晨',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/lake-dawn/400/225`,
    fullUrl: `${PICSUM_BASE}/lake-dawn/1280/720`,
    tags: ['室外', '湖', '清晨', '自然'],
    description: '清晨宁静的湖畔，适合治愈、回忆剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-19',
    name: '繁华餐厅',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/fancy-restaurant/400/225`,
    fullUrl: `${PICSUM_BASE}/fancy-restaurant/1280/720`,
    tags: ['室内', '餐厅', '城市', '约会'],
    description: '精致的餐厅场景，适合约会、商谈剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-20',
    name: '地铁站台',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/subway-platform/400/225`,
    fullUrl: `${PICSUM_BASE}/subway-platform/1280/720`,
    tags: ['室内', '地铁', '城市', '现代'],
    description: '现代地铁站台，适合都市日常、离别剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-21',
    name: '古老城堡',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/ancient-castle/400/225`,
    fullUrl: `${PICSUM_BASE}/ancient-castle/1280/720`,
    tags: ['室外', '城堡', '复古', '奇幻'],
    description: '宏伟的古老城堡，适合奇幻、宫廷剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-22',
    name: '夜晚屋顶',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/rooftop-night/400/225`,
    fullUrl: `${PICSUM_BASE}/rooftop-night/1280/720`,
    tags: ['室外', '屋顶', '夜景', '城市'],
    description: '夜晚的城市屋顶，适合告白、内心独白剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-23',
    name: '樱花树下',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/sakura-tree/400/225`,
    fullUrl: `${PICSUM_BASE}/sakura-tree/1280/720`,
    tags: ['室外', '樱花', '自然', '浪漫'],
    description: '盛开的樱花树下，适合青春恋爱剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-24',
    name: '火车站台',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/train-platform/400/225`,
    fullUrl: `${PICSUM_BASE}/train-platform/1280/720`,
    tags: ['室外', '火车站', '城市', '离别'],
    description: '火车站台场景，适合离别、远行剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-25',
    name: '古老酒馆',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/tavern-old/400/225`,
    fullUrl: `${PICSUM_BASE}/tavern-old/1280/720`,
    tags: ['室内', '酒馆', '复古', '奇幻'],
    description: '古朴的酒馆内景，适合奇幻、冒险剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-26',
    name: '樱花街道',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/sakura-street/400/225`,
    fullUrl: `${PICSUM_BASE}/sakura-street/1280/720`,
    tags: ['室外', '街道', '樱花', '浪漫'],
    description: '樱花飘落的街道，适合浪漫、青春剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-27',
    name: '荒漠废墟',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/desert-ruins/400/225`,
    fullUrl: `${PICSUM_BASE}/desert-ruins/1280/720`,
    tags: ['室外', '废墟', '荒漠', '冒险'],
    description: '荒漠中的废墟，适合末世、冒险剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-28',
    name: '星空草原',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${PICSUM_BASE}/starry-meadow/400/225`,
    fullUrl: `${PICSUM_BASE}/starry-meadow/1280/720`,
    tags: ['室外', '草原', '星空', '夜晚'],
    description: '繁星点点的草原夜空，适合治愈、内心独白剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-29',
    name: '现代客厅',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/modern-livingroom/400/225`,
    fullUrl: `${PICSUM_BASE}/modern-livingroom/1280/720`,
    tags: ['室内', '客厅', '房间', '日常'],
    description: '现代风格的客厅，适合家庭日常剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-30',
    name: '小巷晨雾',
    category: 'background',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/foggy-alley/400/225`,
    fullUrl: `${PICSUM_BASE}/foggy-alley/1280/720`,
    tags: ['室外', '街道', '清晨', '雾'],
    description: '晨雾中的小巷，适合悬疑、回忆剧情。',
    source: 'picsum.photos',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
]

/**
 * 角色立绘占位素材（20 个）
 * 使用 picsum.photos seed 生成 400x600 立绘占位图
 */
const CHARACTER_ASSETS: LibraryAsset[] = [
  {
    id: 'char-01',
    name: '少年立绘 A',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/boy-sprite-a/200/300`,
    fullUrl: `${PICSUM_BASE}/boy-sprite-a/400/600`,
    tags: ['男性', '少年', '日常'],
    description: '少年风格立绘占位图，适合青春校园男主角。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-02',
    name: '少女立绘 A',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/girl-sprite-a/200/300`,
    fullUrl: `${PICSUM_BASE}/girl-sprite-a/400/600`,
    tags: ['女性', '少女', '日常'],
    description: '少女风格立绘占位图，适合青春校园女主角。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-03',
    name: '青年立绘 B',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/boy-sprite-b/200/300`,
    fullUrl: `${PICSUM_BASE}/boy-sprite-b/400/600`,
    tags: ['男性', '青年', '职场'],
    description: '青年职场风格立绘，适合都市、商战剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-04',
    name: '少女立绘 B',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/girl-sprite-b/200/300`,
    fullUrl: `${PICSUM_BASE}/girl-sprite-b/400/600`,
    tags: ['女性', '少女', '可爱'],
    description: '可爱风格少女立绘，适合日常、恋爱剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-05',
    name: '神秘男子',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/mystery-man/200/300`,
    fullUrl: `${PICSUM_BASE}/mystery-man/400/600`,
    tags: ['男性', '青年', '神秘'],
    description: '神秘风格男子立绘，适合悬疑、反派剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-06',
    name: '冷艳女子',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/cool-woman/200/300`,
    fullUrl: `${PICSUM_BASE}/cool-woman/400/600`,
    tags: ['女性', '青年', '冷酷'],
    description: '冷艳风格女子立绘，适合职场、悬疑剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-07',
    name: '少年剑客',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/sword-boy/200/300`,
    fullUrl: `${PICSUM_BASE}/sword-boy/400/600`,
    tags: ['男性', '少年', '奇幻'],
    description: '剑客风格少年立绘，适合奇幻、冒险剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-08',
    name: '魔法少女',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/magic-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/magic-girl/400/600`,
    tags: ['女性', '少女', '奇幻'],
    description: '魔法少女风格立绘，适合奇幻、战斗剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-09',
    name: '老者立绘',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/elder-man/200/300`,
    fullUrl: `${PICSUM_BASE}/elder-man/400/600`,
    tags: ['男性', '老年', '智慧'],
    description: '智慧老者立绘，适合导师、长者剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-10',
    name: '温柔女子',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/gentle-woman/200/300`,
    fullUrl: `${PICSUM_BASE}/gentle-woman/400/600`,
    tags: ['女性', '青年', '温柔'],
    description: '温柔风格女子立绘，适合治愈、家庭剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-11',
    name: '热血少年',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/hotblood-boy/200/300`,
    fullUrl: `${PICSUM_BASE}/hotblood-boy/400/600`,
    tags: ['男性', '少年', '热血'],
    description: '热血风格少年立绘，适合冒险、战斗剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-12',
    name: '优雅少女',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/elegant-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/elegant-girl/400/600`,
    tags: ['女性', '少女', '优雅'],
    description: '优雅风格少女立绘，适合宫廷、贵族剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-13',
    name: '机械少年',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/cyber-boy/200/300`,
    fullUrl: `${PICSUM_BASE}/cyber-boy/400/600`,
    tags: ['男性', '少年', '赛博朋克'],
    description: '赛博朋克风格少年立绘，适合科幻剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-14',
    name: '机甲少女',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/cyber-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/cyber-girl/400/600`,
    tags: ['女性', '少女', '赛博朋克'],
    description: '赛博朋克风格少女立绘，适合科幻剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-15',
    name: '武士青年',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/samurai-man/200/300`,
    fullUrl: `${PICSUM_BASE}/samurai-man/400/600`,
    tags: ['男性', '青年', '武士'],
    description: '武士风格青年立绘，适合历史、战斗剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-16',
    name: '巫女立绘',
    category: 'character',
    license: 'cc-by',
    thumbnailUrl: `${PICSUM_BASE}/miko-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/miko-girl/400/600`,
    tags: ['女性', '少女', '神社'],
    description: '巫女风格少女立绘，适合神社、奇幻剧情。',
    author: 'SubSilicon',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-17',
    name: '少年学生',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/student-boy/200/300`,
    fullUrl: `${PICSUM_BASE}/student-boy/400/600`,
    tags: ['男性', '少年', '学生'],
    description: '学生装少年立绘，适合校园日常剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-18',
    name: '少女学生',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/student-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/student-girl/400/600`,
    tags: ['女性', '少女', '学生'],
    description: '学生装少女立绘，适合校园日常剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-19',
    name: '黑衣男子',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/darkcoat-man/200/300`,
    fullUrl: `${PICSUM_BASE}/darkcoat-man/400/600`,
    tags: ['男性', '青年', '神秘'],
    description: '黑衣神秘男子立绘，适合悬疑、侦探剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-20',
    name: '红衣少女',
    category: 'character',
    license: 'free',
    thumbnailUrl: `${PICSUM_BASE}/redcoat-girl/200/300`,
    fullUrl: `${PICSUM_BASE}/redcoat-girl/400/600`,
    tags: ['女性', '少女', '活泼'],
    description: '红衣活泼少女立绘，适合冒险、恋爱剧情。',
    source: 'picsum.photos',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
]

/**
 * 音效素材（10 个）
 * 仅提供元数据，需创作者自行上传音频文件
 */
const AUDIO_ASSETS: LibraryAsset[] = [
  {
    id: 'audio-01',
    name: '日常 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['BGM', '日常', '轻松'],
    description: '适合日常场景的轻松背景音乐。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-02',
    name: '战斗 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['BGM', '战斗', '激烈'],
    description: '激烈紧张的战斗场景背景音乐。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-03',
    name: '悲伤 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['BGM', '悲伤', '抒情'],
    description: '抒情悲伤的背景音乐，适合离别、回忆场景。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-04',
    name: '恋爱 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['BGM', '恋爱', '甜蜜'],
    description: '甜蜜温柔的恋爱场景背景音乐。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-05',
    name: '悬疑 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['BGM', '悬疑', '紧张'],
    description: '紧张悬疑的背景音乐，适合推理、惊悚场景。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-06',
    name: '咖啡馆环境音',
    category: 'audio',
    license: 'cc0',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['环境音', '咖啡馆', '日常'],
    description: '咖啡馆的环境音效，含轻柔人声与餐具碰撞声。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-07',
    name: '雨夜环境音',
    category: 'audio',
    license: 'cc0',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['环境音', '雨', '夜晚'],
    description: '雨夜的雨声环境音效，适合静谧、悲伤场景。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-08',
    name: '脚步声效果音',
    category: 'audio',
    license: 'cc0',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['效果音', '脚步', '日常'],
    description: '日常脚步声音效，可用于角色进场、转场。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-09',
    name: '开门声效果音',
    category: 'audio',
    license: 'cc0',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['效果音', '门', '日常'],
    description: '开门声效果音，适合场景切换、角色进场。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
  {
    id: 'audio-10',
    name: '铃铛声效果音',
    category: 'audio',
    license: 'cc0',
    thumbnailUrl: '',
    fullUrl: '',
    tags: ['效果音', '铃铛', '提示'],
    description: '清脆的铃铛声效果音，适合提示、过渡场景。需自行上传音频文件。',
    author: '需自行上传',
    source: '官方推荐',
    fileType: 'audio',
  },
]

/**
 * 全部素材（背景图 + 角色立绘 + 音效）
 */
export const LIBRARY_ASSETS: LibraryAsset[] = [
  ...BACKGROUND_ASSETS,
  ...CHARACTER_ASSETS,
  ...AUDIO_ASSETS,
]

/**
 * 按分类筛选素材
 */
export function filterAssetsByCategory(category: AssetCategory | 'all'): LibraryAsset[] {
  if (category === 'all') return LIBRARY_ASSETS
  return LIBRARY_ASSETS.filter((a) => a.category === category)
}

/**
 * 按关键词搜索素材（匹配名称、标签、描述）
 */
export function searchAssets(query: string, assets: LibraryAsset[] = LIBRARY_ASSETS): LibraryAsset[] {
  const q = query.trim().toLowerCase()
  if (!q) return assets
  return assets.filter((a) => {
    return (
      a.name.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.tags.some((t) => t.toLowerCase().includes(q))
    )
  })
}
