/**
 * SubSilicon 官方素材库
 *
 * 提供免费可商用的素材资源，供创作者在编辑器中浏览和使用。
 * 背景图来自 Unsplash (CC0)，角色立绘为人物剪影参考素材，
 * 音效与视频来自 Mixkit (免费可商用)。
 */

export type AssetCategory = 'background' | 'character' | 'item' | 'scene' | 'audio' | 'effect' | 'video'
export type AssetLicense = 'free' | 'cc0' | 'cc-by' | 'commercial'

export interface LibraryAsset {
  id: string
  name: string
  category: AssetCategory
  license: AssetLicense
  thumbnailUrl: string
  fullUrl: string
  tags: string[]
  description: string
  author?: string
  source: string
  dimensions?: { width: number; height: number }
  fileType: 'image' | 'audio' | 'video'
  fileSize?: string
}

const UNSPLASH_BASE = 'https://images.unsplash.com'
const MIXKIT_AUDIO_BASE = 'https://assets.mixkit.co/sfx/preview'
const MIXKIT_VIDEO_BASE = 'https://assets.mixkit.co/videos/preview'

const BACKGROUND_ASSETS: LibraryAsset[] = [
  {
    id: 'bg-01',
    name: '咖啡馆室内',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '咖啡馆', '温暖', '日常', '木质'],
    description: '温暖木质调的咖啡馆内景，有咖啡杯和柔和灯光，适合日常对话与约会剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-02',
    name: '城市霓虹夜景',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '城市', '夜景', '霓虹', '赛博朋克'],
    description: '霓虹灯光映照的城市夜景，高楼林立车水马龙，适合悬疑、赛博朋克故事。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-03',
    name: '校园走廊',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '学校', '走廊', '青春', '明亮'],
    description: '阳光透过窗户的校园走廊，课桌椅排列整齐，适合青春校园剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-04',
    name: '公园晨光草地',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '公园', '自然', '清晨', '绿色'],
    description: '清晨阳光洒落的公园绿地，树木葱郁光影斑驳，适合治愈系、回忆场景。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-05',
    name: '街道黄昏',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '街道', '黄昏', '城市', '夕阳'],
    description: '黄昏时分的城市街道，金色夕阳洒满路面，适合告别、回忆剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-06',
    name: '温馨卧室',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '房间', '温馨', '日常', '卧室'],
    description: '暖色调的温馨卧室，柔软床铺与柔和光线，适合私密对话、内心独白。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-07',
    name: '图书馆书架',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '图书馆', '学校', '安静', '书籍'],
    description: '高耸书架林立的图书馆内景，静谧书香氛围，适合学习、思考剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-08',
    name: '海边夕阳',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '海边', '夕阳', '自然', '浪漫'],
    description: '金色夕阳下的海滩，海浪轻轻拍岸，适合告白、结局场景。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-09',
    name: '森林小径',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1448375240586-882707db888b?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '森林', '自然', '冒险', '绿色'],
    description: '阳光穿透树叶的幽静森林小径，适合冒险、奇幻剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-10',
    name: '雪山湖泊',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '雪山', '自然', '冒险', '湖泊'],
    description: '壮丽的雪山与静谧湖泊，倒映蓝天白云，适合史诗、冒险剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-11',
    name: '教室课桌椅',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '学校', '教室', '青春', '课桌椅'],
    description: '阳光明媚的教室内部，整齐排列的课桌椅，适合校园日常剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-12',
    name: '现代办公室',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '办公室', '城市', '职场', '现代'],
    description: '现代简约风格的办公空间，开放式工位与大落地窗，适合职场、商战剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-13',
    name: '医院走廊',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '医院', '城市', '严肃', '冷色调'],
    description: '冷色调的医院走廊，干净整洁略显压抑，适合严肃、悲伤剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-14',
    name: '繁华商业街',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '街道', '城市', '繁华', '人群'],
    description: '人流如织的商业步行街，霓虹灯闪烁店铺林立，适合都市日常剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-15',
    name: '日式神社',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '神社', '日式', '神秘', '传统'],
    description: '古朴的日式神社建筑，鸟居与石阶，适合奇幻、恋爱剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-16',
    name: '雨夜街道',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1428908728789-d2de25dbd4e2?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1428908728789-d2de25dbd4e2?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '街道', '夜景', '雨', '倒影'],
    description: '雨夜的城市街道，路面倒映着霓虹灯光，适合悬疑、追逐剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-17',
    name: '山顶云海',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '山', '云海', '神秘', '自然'],
    description: '云雾缭绕的山巅之上，仿佛仙境，适合奇幻、修行剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-18',
    name: '湖畔清晨',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室外', '湖', '清晨', '自然', '宁静'],
    description: '清晨薄雾弥漫的宁静湖泊，水面如镜倒映天空，适合治愈、回忆剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-19',
    name: '餐厅约会',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '餐厅', '城市', '约会', '烛光'],
    description: '精致的西餐厅内景，烛光晚餐氛围浪漫，适合约会、商谈剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
  {
    id: 'bg-20',
    name: '地铁站台',
    category: 'background',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1280&q=80`,
    tags: ['室内', '地铁', '城市', '现代', '交通'],
    description: '现代地铁站台，列车驶入乘客等候，适合都市日常、离别剧情。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 1280, height: 720 },
    fileType: 'image',
  },
]

const CHARACTER_ASSETS: LibraryAsset[] = [
  {
    id: 'char-01',
    name: '男性剪影 - 站姿',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['男性', '青年', '日常', '参考'],
    description: '男性人物参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-02',
    name: '女性剪影 - 站姿',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['女性', '青年', '日常', '参考'],
    description: '女性人物参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-03',
    name: '职场男性',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['男性', '青年', '职场', '西装', '参考'],
    description: '职场男性参考素材（西装造型），建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-04',
    name: '职场女性',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['女性', '青年', '职场', '职业装', '参考'],
    description: '职场女性参考素材（职业装造型），建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-05',
    name: '学生 - 男生',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['男性', '少年', '学生', '校园', '参考'],
    description: '少年学生参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-06',
    name: '学生 - 女生',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['女性', '少女', '学生', '校园', '参考'],
    description: '少女学生参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-07',
    name: '休闲男性',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['男性', '青年', '休闲', '日常', '参考'],
    description: '休闲风男性参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-08',
    name: '休闲女性',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['女性', '青年', '休闲', '日常', '参考'],
    description: '休闲风女性参考素材，建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-09',
    name: '年长长者',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1566616213894-2d4e1baee5d8?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1566616213894-2d4e1baee5d8?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['男性', '老年', '智慧', '长者', '参考'],
    description: '年长长者参考素材，适合导师、长辈角色。建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
  {
    id: 'char-10',
    name: '温柔女性',
    category: 'character',
    license: 'cc0',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&h=300&q=60`,
    fullUrl: `${UNSPLASH_BASE}/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&h=600&q=80`,
    tags: ['女性', '青年', '温柔', '治愈', '参考'],
    description: '温柔气质女性参考素材，适合治愈、家庭剧情。建议上传自定义立绘用于正式作品。',
    author: 'Unsplash',
    source: 'unsplash.com',
    dimensions: { width: 400, height: 600 },
    fileType: 'image',
  },
]

const AUDIO_ASSETS: LibraryAsset[] = [
  {
    id: 'audio-01',
    name: '日常轻快 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-ethereal-fairy-win-sound-2019.mp3`,
    tags: ['BGM', '日常', '轻松', '轻快'],
    description: '轻松明快的背景音乐，适合日常、校园场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-02',
    name: '史诗战斗 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-epic-cinematic-trailer-sound-effect-243.mp3`,
    tags: ['BGM', '战斗', '激烈', '史诗'],
    description: '激昂壮阔的史诗级背景音乐，适合战斗、高潮场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-03',
    name: '悲伤钢琴 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-sad-piano-melody-2435.mp3`,
    tags: ['BGM', '悲伤', '抒情', '钢琴'],
    description: '抒情悲伤的钢琴旋律，适合离别、回忆、伤感场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-04',
    name: '浪漫甜蜜 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-romantic-love-moment-2398.mp3`,
    tags: ['BGM', '恋爱', '甜蜜', '浪漫'],
    description: '温柔浪漫的背景音乐，适合恋爱、告白场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-05',
    name: '悬疑紧张 BGM',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-horror-cinematic-impact-2516.mp3`,
    tags: ['BGM', '悬疑', '紧张', '惊悚'],
    description: '紧张悬疑的背景音乐，适合推理、惊悚、转折场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-06',
    name: '咖啡馆环境音',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-inside-a-cafe-ambience-1209.mp3`,
    tags: ['环境音', '咖啡馆', '日常', '嘈杂'],
    description: '咖啡馆环境音效，含轻柔人声与餐具碰撞声，营造日常氛围。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-07',
    name: '雷雨环境音',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-rain-and-thunder-storm-2396.mp3`,
    tags: ['环境音', '雨', '雷', '夜晚'],
    description: '雷雨交加的环境音效，适合静谧、紧张、悲伤场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-08',
    name: '脚步声音效',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-quick-log-steps-1335.mp3`,
    tags: ['效果音', '脚步', '日常', '行走'],
    description: '快速走动的脚步声音效，可用于角色进场、转场。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-09',
    name: '开门锁音效',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-door-locking-1318.mp3`,
    tags: ['效果音', '门', '锁', '日常'],
    description: '门锁咔哒声效果音，适合场景切换、角色进场。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-10',
    name: '提示铃铛声',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-small-bell-notification-985.mp3`,
    tags: ['效果音', '铃铛', '提示', '通知'],
    description: '清脆的铃铛提示音，适合通知、选择、过渡场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-11',
    name: '打字机效果音',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-typewriter-hits-1338.mp3`,
    tags: ['效果音', '打字', '文字', '复古'],
    description: '打字机敲击声效果音，适合文字显示、复古场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
  {
    id: 'audio-12',
    name: '魔法闪光音效',
    category: 'audio',
    license: 'free',
    thumbnailUrl: '',
    fullUrl: `${MIXKIT_AUDIO_BASE}/mixkit-magic-sparkle-notification-2574.mp3`,
    tags: ['效果音', '魔法', '闪光', '奇幻'],
    description: '魔法闪光般的清脆音效，适合奇幻、变身、获得道具场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    fileType: 'audio',
  },
]

const VIDEO_ASSETS: LibraryAsset[] = [
  {
    id: 'video-01',
    name: '城市夜空延时',
    category: 'video',
    license: 'free',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${MIXKIT_VIDEO_BASE}/mixkit-city-lights-reflecting-in-water-317-medium.mp4`,
    tags: ['视频', '城市', '夜景', '延时'],
    description: '城市夜景灯光在水面倒映的延时视频，适合转场、氛围渲染。',
    author: 'Mixkit',
    source: 'mixkit.co',
    dimensions: { width: 640, height: 360 },
    fileType: 'video',
  },
  {
    id: 'video-02',
    name: '雨窗滴落',
    category: 'video',
    license: 'free',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1428908728789-d2de25dbd4e2?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${MIXKIT_VIDEO_BASE}/mixkit-rain-falling-on-a-window-638-medium.mp4`,
    tags: ['视频', '雨', '窗户', '氛围'],
    description: '雨水顺着窗户玻璃滑落的视频，适合雨天、沉思场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    dimensions: { width: 640, height: 360 },
    fileType: 'video',
  },
  {
    id: 'video-03',
    name: '火焰燃烧',
    category: 'video',
    license: 'free',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${MIXKIT_VIDEO_BASE}/mixkit-close-up-of-a-campfire-flames-1568-medium.mp4`,
    tags: ['视频', '火焰', '燃烧', '温暖'],
    description: '篝火火焰静静燃烧的特写视频，适合夜晚、温暖场景。',
    author: 'Mixkit',
    source: 'mixkit.co',
    dimensions: { width: 640, height: 360 },
    fileType: 'video',
  },
  {
    id: 'video-04',
    name: '云朵流动',
    category: 'video',
    license: 'free',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${MIXKIT_VIDEO_BASE}/mixkit-clouds-time-lapse-581-medium.mp4`,
    tags: ['视频', '天空', '云', '延时'],
    description: '天空中云朵快速流动的延时视频，适合时间流逝、转场。',
    author: 'Mixkit',
    source: 'mixkit.co',
    dimensions: { width: 640, height: 360 },
    fileType: 'video',
  },
  {
    id: 'video-05',
    name: '海浪拍打',
    category: 'video',
    license: 'free',
    thumbnailUrl: `${UNSPLASH_BASE}/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=60`,
    fullUrl: `${MIXKIT_VIDEO_BASE}/mixkit-waves-crashing-on-shore-1545-medium.mp4`,
    tags: ['视频', '海', '海浪', '自然'],
    description: '海浪拍打沙滩的视频，适合海边场景、治愈氛围。',
    author: 'Mixkit',
    source: 'mixkit.co',
    dimensions: { width: 640, height: 360 },
    fileType: 'video',
  },
]

export const LIBRARY_ASSETS: LibraryAsset[] = [
  ...BACKGROUND_ASSETS,
  ...CHARACTER_ASSETS,
  ...AUDIO_ASSETS,
  ...VIDEO_ASSETS,
]

export function filterAssetsByCategory(category: AssetCategory | 'all'): LibraryAsset[] {
  if (category === 'all') return LIBRARY_ASSETS
  return LIBRARY_ASSETS.filter((a) => a.category === category)
}

export function searchAssets(query: string, assets: LibraryAsset[] = LIBRARY_ASSETS): LibraryAsset[] {
  const q = query.trim().toLowerCase()
  if (!q) return assets
  return assets.filter((a) => {
    return (
      a.name.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.tags.some((t) => t.toLowerCase().includes(q))
    )
  })
}
